-- BKM DIGITAL
-- Optional catalogue design + contact columns.
-- Safe to run more than once.

alter table public.catalogues
  add column if not exists email text,
  add column if not exists theme text default 'editorial',
  add column if not exists layout text default 'grid',
  add column if not exists accent text default '#111111',
  add column if not exists radius text default 'soft';

-- Gallery rows used by the public catalogue.
-- The app still shows the primary product image if this table is not present.
create table if not exists public.catalogue_product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.catalogue_products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists catalogue_product_images_product_id_idx
  on public.catalogue_product_images(product_id, sort_order);

alter table public.catalogue_product_images enable row level security;

drop policy if exists "Public can view catalogue product images"
  on public.catalogue_product_images;

create policy "Public can view catalogue product images"
  on public.catalogue_product_images
  for select
  to public
  using (true);

drop policy if exists "Public can insert catalogue product images"
  on public.catalogue_product_images;

create policy "Public can insert catalogue product images"
  on public.catalogue_product_images
  for insert
  to public
  with check (true);

drop policy if exists "Public can delete catalogue product images"
  on public.catalogue_product_images;

create policy "Public can delete catalogue product images"
  on public.catalogue_product_images
  for delete
  to public
  using (true);
