-- BKM DIGITAL
-- Product gallery support

create table if not exists public.catalogue_product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.catalogue_products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists catalogue_product_images_product_id_idx
on public.catalogue_product_images(product_id);

create index if not exists catalogue_product_images_sort_order_idx
on public.catalogue_product_images(product_id, sort_order);

alter table public.catalogue_product_images enable row level security;

drop policy if exists "Public can view catalogue product images"
on public.catalogue_product_images;

create policy "Public can view catalogue product images"
on public.catalogue_product_images
for select
to public
using (true);

drop policy if exists "Public can insert catalogue product images"
on public.catalogue_product_images;

create policy "Public can insert catalogue product images"
on public.catalogue_product_images
for insert
to public
with check (true);

-- Migrate existing single-image products into the new gallery.
insert into public.catalogue_product_images (product_id, image_url, sort_order)
select
  id,
  image,
  0
from public.catalogue_products
where image is not null
  and trim(image) <> ''
  and not exists (
    select 1
    from public.catalogue_product_images cpi
    where cpi.product_id = catalogue_products.id
  );
